<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>SteamTools.PlayniteExporter</AssemblyName>
    <RootNamespace>SteamTools.PlayniteExporter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PlayniteSDK" Version="6.*" PrivateAssets="all" />
  </ItemGroup>
</Project>
